*** Variables ***
${tf_name}                       css=input[name="usernameRegisterPage"]
${tf_email}                      css=input[name="emailRegisterPage"]
${tf_password}                   css=input[name="passwordRegisterPage"]
${tf_password_confirm}           css=input[name="confirm_passwordRegisterPage"]
${cb_agree}                      css=input[name="i_agree"]
${btn_confirm}                   id=register_btn